export const abi = [
  {
    "inputs":[
      {
        "internalType":"string",
        "name":"_name",
        "type":"string"
      },
      {
        "internalType":"string",
        "name":"_symbol",
        "type":"string"
      },
      {
        "internalType":"uint256",
        "name":"_maxTokens",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"_maxPerWallet",
        "type":"uint256"
      },
      {
        "internalType":"uint256",
        "name":"_price",
        "type":"uint256"
      }
    ],
    "stateMutability":"nonpayable",
    "type":"constructor"
  },
  {
    "anonymous":false,
    "inputs":[
      {
        "indexed":true,
        "internalType":"address",
        "name":"owner",
        "type":"address"
      },
      {
        "indexed":true,
        "internalType":"address",
        "name":"approved",
        "type":"address"
      },
      {
        "indexed":true,
        "internalType":"uint256",
        "name":"tokenId",
        "type":"uint256"
      }
    ],
    "name":"Approval",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {
        "indexed":true,
        "internalType":"address",
        "name":"owner",
        "type":"address"
      },
      {
        "indexed":true,
        "internalType":"address",
        "name":"operator",
        "type":"address"
      },
      {
        "indexed":false,
        "internalType":"bool",
        "name":"approved",
        "type":"bool"
      }
    ],
    "name":"ApprovalForAll",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {
        "indexed":true,
        "internalType":"address",
        "name":"wallet",
        "type":"address"
      },
      {
        "indexed":true,
        "internalType":"uint256",
        "name":"tokenId",
        "type":"uint256"
      }
    ],
    "name":"CancelReservation",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {
        "indexed":true,
        "internalType":"bytes32",
        "name":"id",
        "type":"bytes32"
      }
    ],
    "name":"ChainlinkCancelled",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {
        "indexed":true,
        "internalType":"bytes32",
        "name":"id",
        "type":"bytes32"
      }
    ],
    "name":"ChainlinkFulfilled",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {
        "indexed":true,
        "internalType":"bytes32",
        "name":"id",
        "type":"bytes32"
      }
    ],
    "name":"ChainlinkRequested",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {
        "indexed":true,
        "internalType":"address",
        "name":"previousOwner",
        "type":"address"
      },
      {
        "indexed":true,
        "internalType":"address",
        "name":"newOwner",
        "type":"address"
      }
    ],
    "name":"OwnershipTransferred",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {
        "indexed":true,
        "internalType":"address",
        "name":"wallet",
        "type":"address"
      },
      {
        "indexed":true,
        "internalType":"uint256",
        "name":"tokenId",
        "type":"uint256"
      }
    ],
    "name":"Reserve",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {
        "indexed":true,
        "internalType":"address",
        "name":"from",
        "type":"address"
      },
      {
        "indexed":true,
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "indexed":true,
        "internalType":"uint256",
        "name":"tokenId",
        "type":"uint256"
      }
    ],
    "name":"Transfer",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {
        "indexed":true,
        "internalType":"address",
        "name":"wallet",
        "type":"address"
      }
    ],
    "name":"Verify",
    "type":"event"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"tokenId",
        "type":"uint256"
      }
    ],
    "name":"approve",
    "outputs":[

    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"owner",
        "type":"address"
      }
    ],
    "name":"balanceOf",
    "outputs":[
      {
        "internalType":"uint256",
        "name":"",
        "type":"uint256"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"id",
        "type":"uint256"
      }
    ],
    "name":"cancelReservation",
    "outputs":[

    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[

    ],
    "name":"chainlinkFee",
    "outputs":[
      {
        "internalType":"uint256",
        "name":"",
        "type":"uint256"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[

    ],
    "name":"chainlinkJobId",
    "outputs":[
      {
        "internalType":"bytes32",
        "name":"",
        "type":"bytes32"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[

    ],
    "name":"chainlinkUrl",
    "outputs":[
      {
        "internalType":"string",
        "name":"",
        "type":"string"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"bytes32",
        "name":"_requestId",
        "type":"bytes32"
      },
      {
        "internalType":"bool",
        "name":"_approved",
        "type":"bool"
      }
    ],
    "name":"fulfillVerification",
    "outputs":[

    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"tokenId",
        "type":"uint256"
      }
    ],
    "name":"getApproved",
    "outputs":[
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[

    ],
    "name":"identityProvider",
    "outputs":[
      {
        "internalType":"contract IProvider",
        "name":"",
        "type":"address"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"_addr",
        "type":"address"
      }
    ],
    "name":"isApproved",
    "outputs":[
      {
        "internalType":"bool",
        "name":"",
        "type":"bool"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"owner",
        "type":"address"
      },
      {
        "internalType":"address",
        "name":"operator",
        "type":"address"
      }
    ],
    "name":"isApprovedForAll",
    "outputs":[
      {
        "internalType":"bool",
        "name":"",
        "type":"bool"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"_addr",
        "type":"address"
      }
    ],
    "name":"isDeclined",
    "outputs":[
      {
        "internalType":"bool",
        "name":"",
        "type":"bool"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"id",
        "type":"uint256"
      }
    ],
    "name":"isMinted",
    "outputs":[
      {
        "internalType":"enum NFT.State",
        "name":"",
        "type":"uint8"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"_addr",
        "type":"address"
      }
    ],
    "name":"isPendingVerification",
    "outputs":[
      {
        "internalType":"bool",
        "name":"",
        "type":"bool"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[

    ],
    "name":"maxPerWallet",
    "outputs":[
      {
        "internalType":"uint256",
        "name":"",
        "type":"uint256"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[

    ],
    "name":"maxTokens",
    "outputs":[
      {
        "internalType":"uint256",
        "name":"",
        "type":"uint256"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"id",
        "type":"uint256"
      }
    ],
    "name":"mint",
    "outputs":[

    ],
    "stateMutability":"payable",
    "type":"function"
  },
  {
    "inputs":[

    ],
    "name":"name",
    "outputs":[
      {
        "internalType":"string",
        "name":"",
        "type":"string"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[

    ],
    "name":"owner",
    "outputs":[
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"tokenId",
        "type":"uint256"
      }
    ],
    "name":"ownerOf",
    "outputs":[
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[

    ],
    "name":"price",
    "outputs":[
      {
        "internalType":"uint256",
        "name":"",
        "type":"uint256"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[

    ],
    "name":"renounceOwnership",
    "outputs":[

    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"id",
        "type":"uint256"
      }
    ],
    "name":"reservedFor",
    "outputs":[
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[

    ],
    "name":"retryVerification",
    "outputs":[

    ],
    "stateMutability":"payable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"from",
        "type":"address"
      },
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"tokenId",
        "type":"uint256"
      }
    ],
    "name":"safeTransferFrom",
    "outputs":[

    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"from",
        "type":"address"
      },
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"tokenId",
        "type":"uint256"
      },
      {
        "internalType":"bytes",
        "name":"data",
        "type":"bytes"
      }
    ],
    "name":"safeTransferFrom",
    "outputs":[

    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"operator",
        "type":"address"
      },
      {
        "internalType":"bool",
        "name":"approved",
        "type":"bool"
      }
    ],
    "name":"setApprovalForAll",
    "outputs":[

    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"string",
        "name":"_uri",
        "type":"string"
      }
    ],
    "name":"setBaseURI",
    "outputs":[

    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"_price",
        "type":"uint256"
      }
    ],
    "name":"setPrice",
    "outputs":[

    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"_provider",
        "type":"address"
      },
      {
        "internalType":"address",
        "name":"_token",
        "type":"address"
      },
      {
        "internalType":"address",
        "name":"_oracle",
        "type":"address"
      },
      {
        "internalType":"bytes32",
        "name":"_jobId",
        "type":"bytes32"
      },
      {
        "internalType":"uint256",
        "name":"_fee",
        "type":"uint256"
      }
    ],
    "name":"setupVerification",
    "outputs":[

    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"bytes4",
        "name":"interfaceId",
        "type":"bytes4"
      }
    ],
    "name":"supportsInterface",
    "outputs":[
      {
        "internalType":"bool",
        "name":"",
        "type":"bool"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[

    ],
    "name":"symbol",
    "outputs":[
      {
        "internalType":"string",
        "name":"",
        "type":"string"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"tokenId",
        "type":"uint256"
      }
    ],
    "name":"tokenURI",
    "outputs":[
      {
        "internalType":"string",
        "name":"",
        "type":"string"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[

    ],
    "name":"totalMinted",
    "outputs":[
      {
        "internalType":"uint256",
        "name":"",
        "type":"uint256"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"from",
        "type":"address"
      },
      {
        "internalType":"address",
        "name":"to",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"tokenId",
        "type":"uint256"
      }
    ],
    "name":"transferFrom",
    "outputs":[

    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"newOwner",
        "type":"address"
      }
    ],
    "name":"transferOwnership",
    "outputs":[

    ],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[

    ],
    "name":"withdraw",
    "outputs":[

    ],
    "stateMutability":"nonpayable",
    "type":"function"
  }
];
